### ISSUE TITLE
Error RUN develop

### ISSUE THREAD

**Issue by vic-badaro** [razinj/strapi-docker-starter#10]
`2022-10-06 04:20:53.759] debug: ⛔️ Server wasn't able to start properly.
[2022-10-06 04:20:53.764] error: role "db_username" does not exist
error: role "db_username" does not exist
    at Parser.parseErrorMessage (/Users/victorocamargo/Documents/CBF/strapi-docker-starter/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/victorocamargo/Documents/CBF/strapi-docker-starter/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/victorocamargo/Documents/CBF/strapi-docker-starter/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/victorocamargo/Documents/CBF/strapi-docker-starter/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)`

**Comment by vic-badaro** [comment]
Help-me? Plz
